/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-surface-variant': '#474740',
        'tertiary-fixed-dim': '#ffb4a7',
        'tertiary-container': '#fff8f7',
        error: '#ba1a1a',
        'primary-container': '#fcf9f2',
        primary: '#5f5e59',
        'on-secondary-fixed': '#231a0f',
        'outline-variant': '#c8c7be',
        tertiary: '#8e4c41',
        'primary-fixed-dim': '#c9c6c0',
        'secondary-fixed-dim': '#d4c4b2',
        outline: '#787770',
        'inverse-surface': '#31302d',
        'on-error-container': '#93000a',
        'error-container': '#ffdad6',
        surface: '#fcf9f4',
        'secondary-fixed': '#f1e0cd',
        'inverse-primary': '#c9c6c0',
        'on-tertiary': '#ffffff',
        'on-background': '#1c1c19',
        'secondary-container': '#f1e0cd',
        'on-secondary': '#ffffff',
        'surface-container-high': '#eae8e3',
        'on-primary': '#ffffff',
        'inverse-on-surface': '#f3f0eb',
        'surface-dim': '#dcdad5',
        'on-tertiary-container': '#a65f54',
        'on-secondary-fixed-variant': '#504538',
        'surface-container-highest': '#e5e2dd',
        'surface-variant': '#e5e2dd',
        'primary-fixed': '#e5e2db',
        secondary: '#695c4e',
        'surface-container-low': '#f6f3ee',
        'surface-bright': '#fcf9f4',
        'surface-container-lowest': '#ffffff',
        'on-primary-fixed-variant': '#474742',
        'on-primary-container': '#73726d',
        'on-surface': '#1c1c19',
        'on-primary-fixed': '#1c1c18',
        'tertiary-fixed': '#ffdad4',
        'on-secondary-container': '#6f6254',
        'surface-tint': '#5f5e59',
        'on-tertiary-fixed-variant': '#71352b',
        'on-error': '#ffffff',
        'on-tertiary-fixed': '#390b05',
        background: '#fcf9f4',
        'surface-container': '#f0ede9',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'margin-desktop': '80px',
        'margin-mobile': '24px',
        base: '8px',
        'section-gap': '160px',
        gutter: '32px',
      },
      maxWidth: {
        page: '1440px',
      },
      fontFamily: {
        'body-md': ['Inter', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
        'display-lg': ['Playfair Display', 'serif'],
        'headline-md': ['Playfair Display', 'serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'display-lg-mobile': ['Playfair Display', 'serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1.0', letterSpacing: '0.1em', fontWeight: '600' }],
        'display-lg': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'display-lg-mobile': ['40px', { lineHeight: '1.2', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
